version: '3.8'
services:
  db:
    image: postgres:15
    volumes: [- postgres_data:/var/lib/postgresql/data/]
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-conflu_db}
      - POSTGRES_USER=${POSTGRES_USER:-conflu_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-conflu_password}
    ports: ["5432:5432"]
  redis:
    image: redis:7-alpine
    volumes: [- redis_data:/data]
    ports: ["6379:6379"]
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: [- .:/app]
    ports: ["8000:8000"]
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on: [- db, - redis]
volumes:
  postgres_data:
  redis_data:
