# Generated by Django 5.2.2 on 2025-06-07 07:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallbackMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_name', models.CharField(max_length=100)),
                ('raw_macro_content', models.TextField()),
                ('import_notes', models.TextField(blank=True, null=True)),
                ('placeholder_id_in_content', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('page_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_macros', to='pages.pageversion')),
            ],
            options={
                'verbose_name': 'Fallback Macro',
                'verbose_name_plural': 'Fallback Macros',
            },
        ),
    ]
