# Generated by Django 5.2.2 on 2025-06-08 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfluenceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded Confluence ZIP export file.', upload_to='confluence_imports/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the file was uploaded.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Current status of the import process.', max_length=20)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID for the import process.', max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confluence_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Confluence Upload',
                'verbose_name_plural': 'Confluence Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
