# Generated by Django 5.2.2 on 2025-06-08 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_confluenceupload'),
        ('workspaces', '0002_alter_space_options_alter_space_owner_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confluenceupload',
            name='target_space',
            field=models.ForeignKey(blank=True, help_text='Optional: The specific space to import content into. Must belong to target_workspace if set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confluence_uploads_targeted_here', to='workspaces.space'),
        ),
        migrations.AddField(
            model_name='confluenceupload',
            name='target_workspace',
            field=models.ForeignKey(blank=True, help_text='Optional: The specific workspace to import content into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confluence_uploads_targeted_here', to='workspaces.workspace'),
        ),
    ]
