# Generated by Django 5.2.2 on 2025-06-08 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_add_target_workspace_space_to_confluenceupload'),
        ('workspaces', '0002_alter_space_options_alter_space_owner_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confluenceupload',
            name='attachments_succeeded_count',
            field=models.IntegerField(default=0, help_text='Number of attachments successfully processed.'),
        ),
        migrations.AddField(
            model_name='confluenceupload',
            name='error_details',
            field=models.TextField(blank=True, help_text='Summary of errors encountered during import.', null=True),
        ),
        migrations.AddField(
            model_name='confluenceupload',
            name='pages_failed_count',
            field=models.IntegerField(default=0, help_text='Number of pages that failed to import.'),
        ),
        migrations.AddField(
            model_name='confluenceupload',
            name='pages_succeeded_count',
            field=models.IntegerField(default=0, help_text='Number of pages successfully imported.'),
        ),
        migrations.AddField(
            model_name='confluenceupload',
            name='progress_message',
            field=models.CharField(blank=True, help_text='Current stage or progress message of the import.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='confluenceupload',
            name='target_space',
            field=models.ForeignKey(blank=True, help_text='Optional: The specific space to import content into. Must belong to target_workspace if set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confluence_uploads_as_target_sp', to='workspaces.space'),
        ),
        migrations.AlterField(
            model_name='confluenceupload',
            name='target_workspace',
            field=models.ForeignKey(blank=True, help_text='Optional: The specific workspace to import content into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confluence_uploads_as_target_ws', to='workspaces.workspace'),
        ),
    ]
