# Generated by Django 5.2.2 on 2025-06-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_add_progress_fields_to_confluenceupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='confluenceupload',
            name='progress_percent',
            field=models.IntegerField(default=0, help_text='Overall progress percentage (0-100).'),
        ),
        migrations.AddField(
            model_name='confluenceupload',
            name='progress_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EXTRACTING', 'Extracting Files'), ('PARSING_METADATA', 'Parsing Metadata'), ('PROCESSING_PAGES', 'Processing Pages'), ('LINKING_HIERARCHY', 'Linking Hierarchy'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Detailed status of the import process for progress tracking.', max_length=30),
        ),
        migrations.AlterField(
            model_name='confluenceupload',
            name='progress_message',
            field=models.TextField(blank=True, help_text='Current stage or progress message of the import.', null=True),
        ),
        migrations.AlterField(
            model_name='confluenceupload',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EXTRACTING', 'Extracting Files'), ('PARSING_METADATA', 'Parsing Metadata'), ('PROCESSING_PAGES', 'Processing Pages'), ('LINKING_HIERARCHY', 'Linking Hierarchy'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Current status of the import process.', max_length=20),
        ),
    ]
