# Generated by Django 5.2.2 on 2025-06-07 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='attachments_placeholder/%Y/%m/%d/')),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('scan_status', models.CharField(choices=[('pending', 'Pending Scan'), ('clean', 'Scan Clean'), ('infected', 'Scan Infected'), ('error', 'Scan Error'), ('skipped', 'Scan Skipped')], db_index=True, default='pending', max_length=20)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pages.page')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
