# Generated by Django 5.2.2 on 2025-06-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_space_options_alter_space_owner_workspace_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['workspace__name', 'name'], 'permissions': [('edit_space_content', 'Can add/edit pages within the space'), ('admin_space', 'Can administer space (manage permissions, settings)')], 'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
    ]
