# Generated by Django 5.2.2 on 2025-06-08 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='raw_content',
        ),
        migrations.RemoveField(
            model_name='pageversion',
            name='raw_content',
        ),
        migrations.AddField(
            model_name='page',
            name='content_json',
            field=models.JSONField(default=dict, help_text='Page content in ProseMirror JSON format.'),
        ),
        migrations.AddField(
            model_name='page',
            name='imported_by',
            field=models.ForeignKey(blank=True, help_text='User who imported this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='original_confluence_id',
            field=models.CharField(blank=True, help_text='Original ID from Confluence, if applicable.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='content_json',
            field=models.JSONField(default=dict, help_text='Page content in ProseMirror JSON format for this version.'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(help_text='Original filename of the attachment.', max_length=255)),
                ('file', models.FileField(help_text='The actual attachment file.', upload_to='page_attachments/%Y/%m/%d/')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the attachment.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, help_text='User who imported this attachment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_attachments', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(help_text='The page this attachment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='page_specific_attachments', to='pages.page')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['original_filename'],
            },
        ),
    ]
