# Generated by Django 5.2.2 on 2025-06-08 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_page_raw_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='parent_page',
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent page for hierarchy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.page'),
        ),
    ]
