# Generated by Django 5.2.2 on 2025-06-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_change_page_parent_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for the page. Auto-generated from title if not provided.', max_length=255, unique=True),
        ),
    ]
