# Generated by Django 5.2.2 on 2025-06-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_add_slug_to_page_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content_json',
            field=models.JSONField(blank=True, default=dict, help_text='Page content in ProseMirror JSON format.', null=True),
        ),
    ]
