# Generated by Django 5.2.2 on 2025-06-09 11:10

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_content_json_nullable'),
    ]

    operations = [
        TrigramExtension(),
        # Alternatively, using RunSQL for broader compatibility or if TrigramExtension is not available
        # migrations.RunSQL(
        #     sql='CREATE EXTENSION IF NOT EXISTS pg_trgm;',
        #     reverse_sql='DROP EXTENSION IF EXISTS pg_trgm;',  # Optional: for rolling back
        # ),
    ]
