# Generated by Django 5.2.2 on 2025-06-09 11:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_enable_pg_trgm_extension'),
        ('workspaces', '0002_alter_space_options_alter_space_owner_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='page',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='pages_page_search__6d0d45_gin'),
        ),
    ]
